<?php


function theme_icons() {
    return [
        'business-atm' => 'business-atm',
        'business-atm-1' => 'business-atm-1',
        'business-atm-2' => 'business-atm-2',
        'business-bag' => 'business-bag',
        'business-bag-1' => 'business-bag-1',
        'business-bag-2' => 'business-bag-2',
        'business-bag-3' => 'business-bag-3',
        'business-bag-4' => 'business-bag-4',
        'business-bag-5' => 'business-bag-5',
        'business-bag-6' => 'business-bag-6',
        'business-bank' => 'business-bank',
        'business-barbershop' => 'business-barbershop',
        'business-barcode' => 'business-barcode',
        'business-barcode-1' => 'business-barcode-1',
        'business-basket' => 'business-basket',
        'business-basket-1' => 'business-basket-1',
        'business-basket-2' => 'business-basket-2',
        'business-box' => 'business-box',
        'business-box-1' => 'business-box-1',
        'business-box-2' => 'business-box-2',
        'business-box-3' => 'business-box-3',
        'business-briefcase' => 'business-briefcase',
        'business-briefcase-1' => 'business-briefcase-1',
        'business-calculator' => 'business-calculator',
        'business-cart' => 'business-cart',
        'business-cart-1' => 'business-cart-1',
        'business-cart-10' => 'business-cart-10',
        'business-cart-11' => 'business-cart-11',
        'business-cart-12' => 'business-cart-12',
        'business-cart-13' => 'business-cart-13',
        'business-cart-14' => 'business-cart-14',
        'business-cart-15' => 'business-cart-15',
        'business-cart-16' => 'business-cart-16',
        'business-cart-17' => 'business-cart-17',
        'business-cart-2' => 'business-cart-2',
        'business-cart-3' => 'business-cart-3',
        'business-cart-4' => 'business-cart-4',
        'business-cart-5' => 'business-cart-5',
        'business-cart-6' => 'business-cart-6',
        'business-cart-7' => 'business-cart-7',
        'business-cart-8' => 'business-cart-8',
        'business-cart-9' => 'business-cart-9',
        'business-cashier' => 'business-cashier',
        'business-cashier-1' => 'business-cashier-1',
        'business-change' => 'business-change',
        'business-check' => 'business-check',
        'business-coin' => 'business-coin',
        'business-coin-1' => 'business-coin-1',
        'business-coin-10' => 'business-coin-10',
        'business-coin-2' => 'business-coin-2',
        'business-coin-3' => 'business-coin-3',
        'business-coin-4' => 'business-coin-4',
        'business-coin-5' => 'business-coin-5',
        'business-coin-6' => 'business-coin-6',
        'business-coin-7' => 'business-coin-7',
        'business-coin-8' => 'business-coin-8',
        'business-coin-9' => 'business-coin-9',
        'business-coins' => 'business-coins',
        'business-coins-1' => 'business-coins-1',
        'business-crate' => 'business-crate',
        'business-crate-1' => 'business-crate-1',
        'business-crate-2' => 'business-crate-2',
        'business-crate-3' => 'business-crate-3',
        'business-crate-4' => 'business-crate-4',
        'business-crate-5' => 'business-crate-5',
        'business-credit-card' => 'business-card',
        'business-credit-card-1' => 'business-credit-card-1',
        'business-credit-card-2' => 'business-credit-card-2',
        'business-credit-card-3' => 'business-credit-card-3',
        'business-credit-card-4' => 'business-credit-card-4',
        'business-credit-card-5' => 'business-credit-card-5',
        'business-credit-card-6' => 'business-credit-card-6',
        'business-delivery-cart' => 'business-delivery-cart',
        'business-delivery-cart-1' => 'business-delivery-cart-1',
        'business-diagram' => 'business-diagram',
        'business-diagram-1' => 'business-diagram-1',
        'business-diagram-2' => 'business-diagram-2',
        'business-diagram-3' => 'business-diagram-3',
        'business-folder' => 'business-folder',
        'business-folder-1' => 'business-folder-1',
        'business-get-money' => 'business-get-money',
        'business-graph' => 'business-graph',
        'business-graph-1' => 'business-graph-1',
        'business-graph-2' => 'business-graph-2',
        'business-graph-3' => 'business-graph-3',
        'business-graph-4' => 'business-graph-4',
        'business-graph-5' => 'business-graph-5',
        'business-graph-6' => 'business-graph-6',
        'business-graph-7' => 'business-graph-7',
        'business-graph-8' => 'business-graph-8',
        'business-grocery' => 'business-grocery',
        'business-grocery-1' => 'business-grocery-1',
        'business-insert-coin' => 'business-insert-coin',
        'business-investment' => 'business-investment',
        'business-justice' => 'business-justice',
        'business-justice-scale' => 'business-justice-scale',
        'business-megaphone' => 'business-megaphone',
        'business-money' => 'business-money',
        'business-notes' => 'business-notes',
        'business-notes-1' => 'business-notes-1',
        'business-notes-2' => 'business-notes-2',
        'business-open' => 'business-open',
        'business-pack' => 'business-pack',
        'business-pie-chart' => 'business-pie-chart',
        'business-pie-chart-1' => 'business-pie-chart-1',
        'business-pie-chart-2' => 'business-pie-chart-2',
        'business-pie-chart-3' => 'business-pie-chart-3',
        'business-pie-chart-4' => 'business-pie-chart-4',
        'business-pie-chart-5' => 'business-pie-chart-5',
        'business-pie-chart-6' => 'business-pie-chart-6',
        'business-piggy-bank' => 'business-piggy-bank',
        'business-piggy-bank-1' => 'business-piggy-bank-1',
        'business-point-of-service' => 'business-point-of-service',
        'business-poor' => 'business-poor',
        'business-presentation' => 'business-presentation',
        'business-presentation-1' => 'business-presentation-1',
        'business-presentation-10' => 'business-presentation-10',
        'business-presentation-11' => 'business-presentation-11',
        'business-presentation-12' => 'business-presentation-12',
        'business-presentation-13' => 'business-presentation-13',
        'business-presentation-14' => 'business-presentation-14',
        'business-presentation-15' => 'business-presentation-15',
        'business-presentation-16' => 'business-presentation-16',
        'business-presentation-17' => 'business-presentation-17',
        'business-presentation-18' => 'business-presentation-18',
        'business-presentation-19' => 'business-presentation-19',
        'business-presentation-2' => 'business-presentation-2',
        'business-presentation-3' => 'business-presentation-3',
        'business-presentation-4' => 'business-presentation-4',
        'business-presentation-5' => 'business-presentation-5',
        'business-presentation-6' => 'business-presentation-6',
        'business-presentation-7' => 'business-presentation-7',
        'business-presentation-8' => 'business-presentation-8',
        'business-presentation-9' => 'business-presentation-9',
        'business-price-tag' => 'business-price-tag',
        'business-price-tag-1' => 'business-price-tag-1',
        'business-price-tag-2' => 'business-price-tag-2',
        'business-price-tag-3' => 'business-price-tag-3',
        'business-price-tag-4' => 'business-price-tag-4',
        'business-price-tag-5' => 'business-price-tag-5',
        'business-price-tag-6' => 'business-price-tag-6',
        'business-price-tag-7' => 'business-price-tag-7',
        'business-price-tag-8' => 'business-price-tag-8',
        'business-price-tag-9' => 'business-price-tag-9',
        'business-receipt' => 'business-receipt',
        'business-record' => 'business-record',
        'business-rewind-time' => 'business-rewind-time',
        'business-rich' => 'business-rich',
        'business-safebox' => 'business-safebox',
        'business-safebox-1' => 'business-safebox-1',
        'business-safebox-2' => 'business-safebox-2',
        'business-safebox-3' => 'business-safebox-3',
        'business-safebox-4' => 'business-safebox-4',
        'business-stamp' => 'business-stamp',
        'business-stamp-1' => 'business-stamp-1',
        'business-stand' => 'business-stand',
        'business-store' => 'business-store',
        'business-store-1' => 'business-store-1',
        'business-store-2' => 'business-store-2',
        'business-store-3' => 'business-store-3',
        'business-strongbox' => 'business-strongbox',
        'business-suitcase' => 'business-suitcase',
        'business-suitcase-1' => 'business-suitcase-1',
        'business-suitcase-2' => 'business-suitcase-2',
        'business-time-is-money' => 'business-time-is-money',
        'business-time-passing' => 'business-time-passing',
        'business-wallet' => 'business-wallet',
        'business-wallet-1' => 'business-wallet-1',
        'business-wallet-2' => 'business-wallet-2',
        'business-yen' => 'business-yen',   

        'industrial-061-blueprint' => 'industrial-061-blueprint', 
        'industrial-061-book' => 'industrial-061-book', 
        'industrial-061-conveyor' => 'industrial-061-conveyor', 
        'industrial-061-conveyor-1' => 'industrial-061-conveyor-1', 
        'industrial-061-conveyor-2' => 'industrial-061-conveyor-2', 
        'industrial-061-conveyor-3' => 'industrial-061-conveyor-3', 
        'industrial-061-conveyor-4' => 'industrial-061-conveyor-4', 
        'industrial-061-conveyor-5' => 'industrial-061-conveyor-5', 
        'industrial-061-conveyor-6' => 'industrial-061-conveyor-6', 
        'industrial-061-conveyor-7' => 'industrial-061-conveyor-7', 
        'industrial-061-crane' => 'industrial-061-crane', 
        'industrial-061-crane-1' => 'industrial-061-crane-1', 
        'industrial-061-crane-2' => 'industrial-061-crane-2', 
        'industrial-061-crane-3' => 'industrial-061-crane-3', 
        'industrial-061-crane-4' => 'industrial-061-crane-4', 
        'industrial-061-dashboard' => 'industrial-061-dashboard', 
        'industrial-061-dashboard-1' => 'industrial-061-dashboard-1', 
        'industrial-061-dashboard-2' => 'industrial-061-dashboard-2', 
        'industrial-061-dashboard-3' => 'industrial-061-dashboard-3', 
        'industrial-061-dashboard-4' => 'industrial-061-dashboard-4', 
        'industrial-061-drilling-machine' => 'industrial-061-drilling-machine', 
        'industrial-061-factory' => 'industrial-061-factory', 
        'industrial-061-factory-1' => 'industrial-061-factory-1', 
        'industrial-061-factory-2' => 'industrial-061-factory-2', 
        'industrial-061-factory-3' => 'industrial-061-factory-3', 
        'industrial-061-factory-4' => 'industrial-061-factory-4', 
        'industrial-061-factory-5' => 'industrial-061-factory-5', 
        'industrial-061-factory-6' => 'industrial-061-factory-6', 
        'industrial-061-industrial-robot' => 'industrial-061-industrial-robot', 
        'industrial-061-industrial-robot-1' => 'industrial-061-industrial-robot-1', 
        'industrial-061-industrial-robot-10' => 'industrial-061-industrial-robot-10', 
        'industrial-061-industrial-robot-11' => 'industrial-061-industrial-robot-11', 
        'industrial-061-industrial-robot-12' => 'industrial-061-industrial-robot-12', 
        'industrial-061-industrial-robot-13' => 'industrial-061-industrial-robot-13', 
        'industrial-061-industrial-robot-14' => 'industrial-061-industrial-robot-14', 
        'industrial-061-industrial-robot-15' => 'industrial-061-industrial-robot-15', 
        'industrial-061-industrial-robot-16' => 'industrial-061-industrial-robot-16', 
        'industrial-061-industrial-robot-17' => 'industrial-061-industrial-robot-17', 
        'industrial-061-industrial-robot-2' => 'industrial-061-industrial-robot-2', 
        'industrial-061-industrial-robot-3' => 'industrial-061-industrial-robot-3',
        'industrial-061-industrial-robot-4' => 'industrial-061-industrial-robot-4', 
        'industrial-061-industrial-robot-5' => 'industrial-061-industrial-robot-5',
        'industrial-061-industrial-robot-6' => 'industrial-061-industrial-robot-6', 
        'industrial-061-industrial-robot-7' => 'industrial-061-industrial-robot-7',
        'industrial-061-industrial-robot-8' => 'industrial-061-industrial-robot-8', 
        'industrial-061-industrial-robot-9' => 'industrial-061-industrial-robot-9', 
        'industrial-061-machine-press' => 'industrial-061-machine-press', 
        'industrial-061-machine-press-1' => 'industrial-061-machine-press-1',
        'industrial-061-machine-press-2' => 'industrial-061-machine-press-2', 
        'industrial-061-machine-press-3' => 'industrial-061-machine-press-3',
        'industrial-061-machine-press-4' => 'industrial-061-machine-press-4', 
        'industrial-061-machine-press-5' => 'industrial-061-machine-press-5',
        'industrial-061-packages' => 'industrial-061-packages', 
        'industrial-061-power-plant' => 'industrial-061-power-plant', 
        'industrial-061-processor' => 'industrial-061-processor', 
        'industrial-061-refinery' => 'industrial-061-refinery',
        'industrial-061-refinery-1' => 'industrial-061-refinery-1', 
        'industrial-061-refinery-2' => 'industrial-061-refinery-2',
        'industrial-061-stock' => 'industrial-061-stock', 
        'industrial-061-welder' => 'industrial-061-welder', 
        
        'seo-analytics' => 'seo-analytics',
        'seo-analytics-1' => 'seo-analytics-1',
        'seo-analytics-10' => 'seo-analytics-10',
        'seo-analytics-11' => 'seo-analytics-11',
        'seo-analytics-12' => 'seo-analytics-12',
        'seo-analytics-13' => 'seo-analytics-13',
        'seo-analytics-14' => 'seo-analytics-14',
        'seo-analytics-15' => 'seo-analytics-15',
        'seo-analytics-16' => 'seo-analytics-16',
        'seo-analytics-17' => 'seo-analytics-17',
        'seo-analytics-18' => 'seo-analytics-18',
        'seo-analytics-19' => 'seo-analytics-19',
        'seo-analytics-2' => 'seo-analytics-2',
        'seo-analytics-20' => 'seo-analytics-20',
        'seo-analytics-21' => 'seo-analytics-21',
        'seo-analytics-22' => 'seo-analytics-22',
        'seo-analytics-23' => 'seo-analytics-23',
        'seo-analytics-24' => 'seo-analytics-24',
        'seo-analytics-25' => 'seo-analytics-25',
        'seo-analytics-26' => 'seo-analytics-26',
        'seo-analytics-3' => 'seo-analytics-3',
        'seo-analytics-4' => 'seo-analytics-4',
        'seo-analytics-5' => 'seo-analytics-5',
        'seo-analytics-6' => 'seo-analytics-6',
        'seo-analytics-7' => 'seo-analytics-7',
        'seo-analytics-8' => 'seo-analytics-8',
        'seo-analytics-9' => 'seo-analytics-9',
        'seo-browser' => 'seo-browser',
        'seo-browser-1' => 'seo-browser-1',
        'seo-browser-10' => 'seo-browser-10',
        'seo-browser-11' => 'seo-browser-11',
        'seo-browser-12' => 'seo-browser-12',
        'seo-browser-13' => 'seo-browser-13',
        'seo-browser-14' => 'seo-browser-14',
        'seo-browser-15' => 'seo-browser-15',
        'seo-browser-16' => 'seo-browser-16',
        'seo-browser-17' => 'seo-browser-17',
        'seo-browser-18' => 'seo-browser-18',
        'seo-browser-19' => 'seo-browser-19',
        'seo-browser-2' => 'seo-browser-2',
        'seo-browser-20' => 'seo-browser-20',
        'seo-browser-21' => 'seo-browser-21',
        'seo-browser-22' => 'seo-browser-22',
        'seo-browser-23' => 'seo-browser-23',
        'seo-browser-24' => 'seo-browser-24',
        'seo-browser-25' => 'seo-browser-25',
        'seo-browser-26' => 'seo-browser-26',
        'seo-browser-27' => 'seo-browser-27',
        'seo-browser-28' => 'seo-browser-28',
        'seo-browser-29' => 'seo-browser-29',
        'seo-browser-3' => 'seo-browser-3',
        'seo-browser-30' => 'seo-browser-30',
        'seo-browser-31' => 'seo-browser-31',
        'seo-browser-32' => 'seo-browser-32',
        'seo-browser-33' => 'seo-browser-33',
        'seo-browser-34' => 'seo-browser-34',
        'seo-browser-35' => 'seo-browser-35',
        'seo-browser-36' => 'seo-browser-36',
        'seo-browser-37' => 'seo-browser-37',
        'seo-browser-38' => 'seo-browser-38',
        'seo-browser-39' => 'seo-browser-39',
        'seo-browser-4' => 'seo-browser-4',
        'seo-browser-40' => 'seo-browser-40',
        'seo-browser-41' => 'seo-browser-41',
        'seo-browser-42' => 'seo-browser-42',
        'seo-browser-43' => 'seo-browser-43',
        'seo-browser-44' => 'seo-browser-44',
        'seo-browser-45' => 'seo-browser-45',
        'seo-browser-46' => 'seo-browser-46',
        'seo-browser-47' => 'seo-browser-47',
        'seo-browser-5' => 'seo-browser-5',
        'seo-browser-6' => 'seo-browser-6',
        'seo-browser-7' => 'seo-browser-7',
        'seo-browser-8' => 'seo-browser-8',
        'seo-browser-9' => 'seo-browser-9',
        'seo-cloud-computing' => 'seo-cloud-computing',
        'seo-cloud-computing-1' => 'seo-cloud-computing-1',
        'seo-cloud-computing-2' => 'seo-cloud-computing-2',
        'seo-cloud-computing-3' => 'seo-cloud-computing-3',
        'seo-cloud-computing-4' => 'seo-cloud-computing-4',
        'seo-cloud-computing-5' => 'seo-cloud-computing-5',
        'seo-network' => 'seo-network',
        'seo-network-1' => 'seo-network-1',
        'seo-networking' => 'seo-networking',
        'seo-pie-chart' => 'seo-pie-chart',
        'seo-pie-chart-1' => 'seo-pie-chart-1',
        'seo-pie-chart-2' => 'seo-pie-chart-2',
        'seo-pie-chart-3' => 'seo-pie-chart-3',
        'seo-pie-chart-4' => 'seo-pie-chart-4',
        'seo-pie-chart-5' => 'seo-pie-chart-5',
        'seo-pie-chart-6' => 'seo-pie-chart-6',
        'seo-pie-chart-7' => 'seo-pie-chart-7',
        'seo-pie-chart-8' => 'seo-pie-chart-8',
        'seo-pie-chart-9' => 'seo-pie-chart-9',
        'seo-server' => 'seo-server',
        'seo-smartphone' => 'seo-smartphone',
        'seo-smartphone-1' => 'seo-smartphone-1',
        'seo-smartphone-2' => 'seo-smartphone-2',
        'seo-worldwide' => 'seo-worldwide',
        'seo-worldwide-1' => 'seo-worldwide-1',
        'seo-worldwide-10' => 'seo-worldwide-10',
        'seo-worldwide-11' => 'seo-worldwide-11',
        'seo-worldwide-12' => 'seo-worldwide-12',
        'seo-worldwide-13' => 'seo-worldwide-13',
        'seo-worldwide-14' => 'seo-worldwide-14',
        'seo-worldwide-15' => 'seo-worldwide-15',
        'seo-worldwide-16' => 'seo-worldwide-16',
        'seo-worldwide-17' => 'seo-worldwide-17',
        'seo-worldwide-18' => 'seo-worldwide-18',
        'seo-worldwide-19' => 'seo-worldwide-19',
        'seo-worldwide-2' => 'seo-worldwide-2',
        'seo-worldwide-20' => 'seo-worldwide-20',
        'seo-worldwide-21' => 'seo-worldwide-21',
        'seo-worldwide-3' => 'seo-worldwide-3',
        'seo-worldwide-4' => 'seo-worldwide-4',
        'seo-worldwide-5' => 'seo-worldwide-5',
        'seo-worldwide-6' => 'seo-worldwide-6',
        'seo-worldwide-7' => 'seo-worldwide-7',
        'seo-worldwide-8' => 'seo-worldwide-8',
        'seo-worldwide-9' => 'seo-worldwide-9', 


        'image-001-curves' => 'image-001-curves',
        'image-002-levels-1' => 'image-002-levels-1',
        'image-003-brightness-2' => 'image-003-brightness-2',
        'image-004-pixelated' => 'image-004-pixelated',
        'image-005-sponge' => 'image-005-sponge',
        'image-006-cd-burn' => 'image-006-cd-burn',
        'image-007-brightness-1' => 'image-007-brightness-1',
        'image-008-color' => 'image-008-color',
        'image-009-monitor-7' => 'image-009-monitor-7',
        'image-010-monitor-6' => 'image-010-monitor-6',
        'image-011-monitor-5' => 'image-011-monitor-5',
        'image-012-levels' => 'image-012-levels',
        'image-013-magic-wand' => 'image-013-magic-wand',
        'image-014-dropper' => 'image-014-dropper',
        'image-015-adjustment' => 'image-015-adjustment',
        'image-016-photography' => 'image-016-photography',
        'image-017-red-eye-1' => 'image-017-red-eye-1',
        'image-018-patch' => 'image-018-patch',
        'image-019-monitor-4' => 'image-019-monitor-4',
        'image-020-red-eye' => 'image-020-red-eye',
        'image-021-monitor-3' => 'image-021-monitor-3',
        'image-022-monitor-2' => 'image-022-monitor-2',
        'image-023-monitor-1' => 'image-023-monitor-1',
        'image-024-monitor' => 'image-024-monitor',
        'image-025-contrast-1' => 'image-025-contrast-1',
        'image-026-opacity' => 'image-026-opacity',
        'image-027-blur' => 'image-027-blur',
        'image-028-rgb' => 'image-028-rgb',
        'image-029-thermometer' => 'image-029-thermometer',
        'image-030-sliders' => 'image-030-sliders',
        'image-031-pyramid' => 'image-031-pyramid',
        'image-032-crop' => 'image-032-crop',
        'image-033-contrast' => 'image-033-contrast',
        'image-034-brightness' => 'image-034-brightness',
        'image-035-graphic-tablet-5' => 'image-035-graphic-tablet-5',
        'image-036-graphic-tablet-4' => 'image-036-graphic-tablet-4',
        'image-037-graphic-tablet-3' => 'image-037-graphic-tablet-3',
        'image-038-graphic-tablet-2' => 'image-038-graphic-tablet-2',
        'image-039-graphic-tablet-1' => 'image-039-graphic-tablet-1',
        'image-040-graphic-tablet' => 'image-040-graphic-tablet',

        'other-baby-boy' => 'other-baby-boy',
        'other-strong' => 'other-strong',
        'other-sugar-blood-level' => 'other-sugar-blood-level',


        'startups-001-employee-3' => 'startups-001-employee-3',
        'startups-002-employee-2' => 'startups-002-employee-2',
        'startups-003-employee-1' => 'startups-003-employee-1',
        'startups-004-employee' => 'startups-004-employee',
        'startups-005-event' => 'startups-005-event',
        'startups-006-puzzle' => 'startups-006-puzzle',
        'startups-007-computer-1' => 'startups-007-computer-1',
        'startups-008-browser-1' => 'startups-008-browser-1',
        'startups-009-smartphone-1' => 'startups-009-smartphone-1',
        'startups-010-smartphone' => 'startups-010-smartphone',
        'startups-011-networking-1' => 'startups-011-networking-1',
        'startups-012-rocket-1' => 'startups-012-rocket-1',
        'startups-013-laptop' => 'startups-013-laptop',
        'startups-014-briefcase' => 'startups-014-briefcase',
        'startups-015-time-management' => 'startups-015-time-management',
        'startups-016-package' => 'startups-016-package',
        'startups-017-target' => 'startups-017-target',
        'startups-018-clipboard-1' => 'startups-018-clipboard-1',
        'startups-019-clipboard' => 'startups-019-clipboard',
        'startups-020-hourglass' => 'startups-020-hourglass',
        'startups-021-folder' => 'startups-021-folder',
        'startups-022-growth-4' => 'startups-022-growth-4',
        'startups-023-growth-3' => 'startups-023-growth-3',
        'startups-024-growth-2' => 'startups-024-growth-2',
        'startups-025-compass' => 'startups-025-compass',
        'startups-026-wallet' => 'startups-026-wallet',
        'startups-027-growth-1' => 'startups-027-growth-1',
        'startups-028-vision' => 'startups-028-vision',
        'startups-029-presentation' => 'startups-029-presentation',
        'startups-030-computer' => 'startups-030-computer',
        'startups-031-clock' => 'startups-031-clock',
        'startups-032-binoculars' => 'startups-032-binoculars',
        'startups-033-growth' => 'startups-033-growth',
        'startups-034-money-bag' => 'startups-034-money-bag',
        'startups-035-trophy' => 'startups-035-trophy',
        'startups-036-megaphone' => 'startups-036-megaphone',
        'startups-037-browser' => 'startups-037-browser',
        'startups-038-innovation-1' => 'startups-038-innovation-1',
        'startups-039-search' => 'startups-039-search',
        'startups-040-idea' => 'startups-040-idea',
        'startups-041-innovation' => 'startups-041-innovation',
        'startups-042-chat-bubble' => 'startups-042-chat-bubble',
        'startups-043-line-chart' => 'startups-043-line-chart',
        'startups-044-calculator' => 'startups-044-calculator',
        'startups-045-money' => 'startups-045-money',
        'startups-046-mountain' => 'startups-046-mountain',
        'startups-047-loss' => 'startups-047-loss',
        'startups-048-increase' => 'startups-048-increase',
        'startups-049-networking' => 'startups-049-networking',
        'startups-050-rocket' => 'startups-050-rocket',

        'ti-wand' => 'ti-wand',
        'ti-volume' => 'ti-volume',
        'ti-user' => 'ti-user',
        'ti-unlock' => 'ti-unlock',
        'ti-unlink' => 'ti-unlink',
        'ti-trash' => 'ti-trash',
        'ti-thought' => 'ti-thought',
        'ti-target' => 'ti-target',
        'ti-tag' => 'ti-tag',
        'ti-tablet' => 'ti-tablet',
        'ti-star' => 'ti-star',
        'ti-spray' => 'ti-spray',
        'ti-signal' => 'ti-signal',
        'ti-shopping-cart' => 'ti-shopping-cart',
        'ti-shopping-cart-full' => 'ti-shopping-cart-full',
        'ti-settings' => 'ti-settings',
        'ti-search' => 'ti-search',
        'ti-zoom-in' => 'ti-zoom-in',
        'ti-zoom-out' => 'ti-zoom-out',
        'ti-cut' => 'ti-cut',
        'ti-ruler' => 'ti-ruler',
        'ti-ruler-pencil' => 'ti-ruler-pencil',
        'ti-ruler-alt' => 'ti-ruler-alt',
        'ti-bookmark' => 'ti-bookmark',
        'ti-bookmark-alt' => 'ti-bookmark-alt',
        'ti-reload' => 'ti-reload',
        'ti-plus' => 'ti-plus',
        'ti-pin' => 'ti-pin',
        'ti-pencil' => 'ti-pencil',
        'ti-pencil-alt' => 'ti-pencil-alt',
        'ti-paint-roller' => 'ti-paint-roller',
        'ti-paint-bucket' => 'ti-paint-bucket',
        'ti-na' => 'ti-na',
        'ti-mobile' => 'ti-mobile',
        'ti-minus' => 'ti-minus',
        'ti-medall' => 'ti-medall',
        'ti-medall-alt' => 'ti-medall-alt',
        'ti-marker' => 'ti-marker',
        'ti-marker-alt' => 'ti-marker-alt',
        'ti-arrow-up' => 'ti-arrow-up',
        'ti-arrow-right' => 'ti-arrow-right',
        'ti-arrow-left' => 'ti-arrow-left',
        'ti-arrow-down' => 'ti-arrow-down',
        'ti-lock' => 'ti-lock',
        'ti-location-arrow' => 'ti-location-arrow',
        'ti-link' => 'ti-link',
        'ti-layout' => 'ti-layout',
        'ti-layers' => 'ti-layers',
        'ti-layers-alt' => 'ti-layers-alt',
        'ti-key' => 'ti-key',
        'ti-import' => 'ti-import',
        'ti-image' => 'ti-image',
        'ti-heart' => 'ti-heart',
        'ti-heart-broken' => 'ti-heart-broken',
        'ti-hand-stop' => 'ti-hand-stop',
        'ti-hand-open' => 'ti-hand-open',
        'ti-hand-drag' => 'ti-hand-drag',
        'ti-folder' => 'ti-folder',
        'ti-flag' => 'ti-flag',
        'ti-flag-alt' => 'ti-flag-alt',
        'ti-flag-alt-2' => 'ti-flag-alt-2',
        'ti-eye' => 'ti-eye',
        'ti-export' => 'ti-export',
        'ti-exchange-vertical' => 'ti-exchange-vertical',
        'ti-desktop' => 'ti-desktop',
        'ti-cup' => 'ti-cup',
        'ti-crown' => 'ti-crown',
        'ti-comments' => 'ti-comments',
        'ti-comment' => 'ti-comment',
        'ti-comment-alt' => 'ti-comment-alt',
        'ti-close' => 'ti-close',
        'ti-clip' => 'ti-clip',
        'ti-angle-up' => 'ti-angle-up',
        'ti-angle-right' => 'ti-angle-right',
        'ti-angle-left' => 'ti-angle-left',
        'ti-angle-down' => 'ti-angle-down',
        'ti-check' => 'ti-check',
        'ti-check-box' => 'ti-check-box',
        'ti-camera' => 'ti-camera',
        'ti-announcement' => 'ti-announcement',
        'ti-brush' => 'ti-brush',
        'ti-briefcase' => 'ti-briefcase',
        'ti-bolt' => 'ti-bolt',
        'ti-bolt-alt' => 'ti-bolt-alt',
        'ti-blackboard' => 'ti-blackboard',
        'ti-bag' => 'ti-bag',
        'ti-move' => 'ti-move',
        'ti-arrows-vertical' => 'ti-arrows-vertical',
        'ti-arrows-horizontal' => 'ti-arrows-horizontal',
        'ti-fullscreen' => 'ti-fullscreen',
        'ti-arrow-top-right' => 'ti-arrow-top-right',
        'ti-arrow-top-left' => 'ti-arrow-top-left',
        'ti-arrow-circle-up' => 'ti-arrow-circle-up',
        'ti-arrow-circle-right' => 'ti-arrow-circle-right',
        'ti-arrow-circle-left' => 'ti-arrow-circle-left',
        'ti-arrow-circle-down' => 'ti-arrow-circle-down',
        'ti-angle-double-up' => 'ti-angle-double-up',
        'ti-angle-double-right' => 'ti-angle-double-right',
        'ti-angle-double-left' => 'ti-angle-double-left',
        'ti-angle-double-down' => 'ti-angle-double-down',
        'ti-zip' => 'ti-zip',
        'ti-world' => 'ti-world',
        'ti-wheelchair' => 'ti-wheelchair',
        'ti-view-list' => 'ti-view-list',
        'ti-view-list-alt' => 'ti-view-list-alt',
        'ti-view-grid' => 'ti-view-grid',
        'ti-uppercase' => 'ti-uppercase',
        'ti-upload' => 'ti-upload',
        'ti-underline' => 'ti-underline',
        'ti-truck' => 'ti-truck',
        'ti-timer' => 'ti-timer',
        'ti-ticket' => 'ti-ticket',
        'ti-thumb-up' => 'ti-thumb-up',
        'ti-thumb-down' => 'ti-thumb-down',
        'ti-text' => 'ti-text',
        'ti-stats-up' => 'ti-stats-up',
        'ti-stats-down' => 'ti-stats-down',
        'ti-split-v' => 'ti-split-v',
        'ti-split-h' => 'ti-split-h',
        'ti-smallcap' => 'ti-smallcap',
        'ti-shine' => 'ti-shine',
        'ti-shift-right' => 'ti-shift-right',
        'ti-shift-left' => 'ti-shift-left',
        'ti-shield' => 'ti-shield',
        'ti-notepad' => 'ti-notepad',
        'ti-server' => 'ti-server',
        'ti-quote-right' => 'ti-quote-right',
        'ti-quote-left' => 'ti-quote-left',
        'ti-pulse' => 'ti-pulse',
        'ti-printer' => 'ti-printer',
        'ti-power-off' => 'ti-power-off',
        'ti-plug' => 'ti-plug',
        'ti-pie-chart' => 'ti-pie-chart',
        'ti-paragraph' => 'ti-paragraph',
        'ti-panel' => 'ti-panel',
        'ti-package' => 'ti-package',
        'ti-music' => 'ti-music',
        'ti-music-alt' => 'ti-music-alt',
        'ti-mouse' => 'ti-mouse',
        'ti-mouse-alt' => 'ti-mouse-alt',
        'ti-money' => 'ti-money',
        'ti-microphone' => 'ti-microphone',
        'ti-menu' => 'ti-menu',
        'ti-menu-alt' => 'ti-menu-alt',
        'ti-map' => 'ti-map',
        'ti-map-alt' => 'ti-map-alt',
        'ti-loop' => 'ti-loop',
        'ti-location-pin' => 'ti-location-pin',
        'ti-list' => 'ti-list',
        'ti-light-bulb' => 'ti-light-bulb',
        'ti-Italic' => 'ti-Italic',
        'ti-info' => 'ti-info',
        'ti-infinite' => 'ti-infinite',
        'ti-id-badge' => 'ti-id-badge',
        'ti-hummer' => 'ti-hummer',
        'ti-home' => 'ti-home',
        'ti-help' => 'ti-help',
        'ti-headphone' => 'ti-headphone',
        'ti-harddrives' => 'ti-harddrives',
        'ti-harddrive' => 'ti-harddrive',
        'ti-gift' => 'ti-gift',
        'ti-game' => 'ti-game',
        'ti-filter' => 'ti-filter',
        'ti-files' => 'ti-files',
        'ti-file' => 'ti-file',
        'ti-eraser' => 'ti-eraser',
        'ti-envelope' => 'ti-envelope',
        'ti-download' => 'ti-download',
        'ti-direction' => 'ti-direction',
        'ti-direction-alt' => 'ti-direction-alt',
        'ti-dashboard' => 'ti-dashboard',
        'ti-control-stop' => 'ti-control-stop',
        'ti-control-shuffle' => 'ti-control-shuffle',
        'ti-control-play' => 'ti-control-play',
        'ti-control-pause' => 'ti-control-pause',
        'ti-control-forward' => 'ti-control-forward',
        'ti-control-backward' => 'ti-control-backward',
        'ti-cloud' => 'ti-cloud',
        'ti-cloud-up' => 'ti-cloud-up',
        'ti-cloud-down' => 'ti-cloud-down',
        'ti-clipboard' => 'ti-clipboard',
        'ti-car' => 'ti-car',
        'ti-calendar' => 'ti-calendar',
        'ti-book' => 'ti-book',
        'ti-bell' => 'ti-bell',
        'ti-basketball' => 'ti-basketball',
        'ti-bar-chart' => 'ti-bar-chart',
        'ti-bar-chart-alt' => 'ti-bar-chart-alt',
        'ti-back-right' => 'ti-back-right',
        'ti-back-left' => 'ti-back-left',
        'ti-arrows-corner' => 'ti-arrows-corner',
        'ti-archive' => 'ti-archive',
        'ti-anchor' => 'ti-anchor',
        'ti-align-right' => 'ti-align-right',
        'ti-align-left' => 'ti-align-left',
        'ti-align-justify' => 'ti-align-justify',
        'ti-align-center' => 'ti-align-center',
        'ti-alert' => 'ti-alert',
        'ti-alarm-clock' => 'ti-alarm-clock',
        'ti-agenda' => 'ti-agenda',
        'ti-write' => 'ti-write',
        'ti-window' => 'ti-window',
        'ti-widgetized' => 'ti-widgetized',
        'ti-widget' => 'ti-widget',
        'ti-widget-alt' => 'ti-widget-alt',
        'ti-wallet' => 'ti-wallet',
        'ti-video-clapper' => 'ti-video-clapper',
        'ti-video-camera' => 'ti-video-camera',
        'ti-vector' => 'ti-vector',
        'ti-themify-logo' => 'ti-themify-logo',
        'ti-themify-favicon' => 'ti-themify-favicon',
        'ti-themify-favicon-alt' => 'ti-themify-favicon-alt',
        'ti-support' => 'ti-support',
        'ti-stamp' => 'ti-stamp',
        'ti-split-v-alt' => 'ti-split-v-alt',
        'ti-slice' => 'ti-slice',
        'ti-shortcode' => 'ti-shortcode',
        'ti-shift-right-alt' => 'ti-shift-right-alt',
        'ti-shift-left-alt' => 'ti-shift-left-alt',
        'ti-ruler-alt-2' => 'ti-ruler-alt-2',
        'ti-receipt' => 'ti-receipt',
        'ti-pin2' => 'ti-pin2',
        'ti-pin-alt' => 'ti-pin-alt',
        'ti-pencil-alt2' => 'ti-pencil-alt2',
        'ti-palette' => 'ti-palette',
        'ti-more' => 'ti-more',
        'ti-more-alt' => 'ti-more-alt',
        'ti-microphone-alt' => 'ti-microphone-alt',
        'ti-magnet' => 'ti-magnet',
        'ti-line-double' => 'ti-line-double',
        'ti-line-dotted' => 'ti-line-dotted',
        'ti-line-dashed' => 'ti-line-dashed',
        'ti-layout-width-full' => 'ti-layout-width-full',
        'ti-layout-width-default' => 'ti-layout-width-default',
        'ti-layout-width-default-alt' => 'ti-layout-width-default-alt',
        'ti-layout-tab' => 'ti-layout-tab',
        'ti-layout-tab-window' => 'ti-layout-tab-window',
        'ti-layout-tab-v' => 'ti-layout-tab-v',
        'ti-layout-tab-min' => 'ti-layout-tab-min',
        'ti-layout-slider' => 'ti-layout-slider',
        'ti-layout-slider-alt' => 'ti-layout-slider-alt',
        'ti-layout-sidebar-right' => 'ti-layout-sidebar-right',
        'ti-layout-sidebar-none' => 'ti-layout-sidebar-none',
        'ti-layout-sidebar-left' => 'ti-layout-sidebar-left',
        'ti-layout-placeholder' => 'ti-layout-placeholder',
        'ti-layout-menu' => 'ti-layout-menu',
        'ti-layout-menu-v' => 'ti-layout-menu-v',
        'ti-layout-menu-separated' => 'ti-layout-menu-separated',
        'ti-layout-menu-full' => 'ti-layout-menu-full',
        'ti-layout-media-right-alt' => 'ti-layout-media-right-alt',
        'ti-layout-media-right' => 'ti-layout-media-right',
        'ti-layout-media-overlay' => 'ti-layout-media-overlay',
        'ti-layout-media-overlay-alt' => 'ti-layout-media-overlay-alt',
        'ti-layout-media-overlay-alt-2' => 'ti-layout-media-overlay-alt-2',
        'ti-layout-media-left-alt' => 'ti-layout-media-left-alt',
        'ti-layout-media-left' => 'ti-layout-media-left',
        'ti-layout-media-center-alt' => 'ti-layout-media-center-alt',
        'ti-layout-media-center' => 'ti-layout-media-center',
        'ti-layout-list-thumb' => 'ti-layout-list-thumb',
        'ti-layout-list-thumb-alt' => 'ti-layout-list-thumb-alt',
        'ti-layout-list-post' => 'ti-layout-list-post',
        'ti-layout-list-large-image' => 'ti-layout-list-large-image',
        'ti-layout-line-solid' => 'ti-layout-line-solid',
        'ti-layout-grid4' => 'ti-layout-grid4',
        'ti-layout-grid3' => 'ti-layout-grid3',
        'ti-layout-grid2' => 'ti-layout-grid2',
        'ti-layout-grid2-thumb' => 'ti-layout-grid2-thumb',
        'ti-layout-cta-right' => 'ti-layout-cta-right',
        'ti-layout-cta-left' => 'ti-layout-cta-left',
        'ti-layout-cta-center' => 'ti-layout-cta-center',
        'ti-layout-cta-btn-right' => 'ti-layout-cta-btn-right',
        'ti-layout-cta-btn-left' => 'ti-layout-cta-btn-left',
        'ti-layout-column4' => 'ti-layout-column4',
        'ti-layout-column3' => 'ti-layout-column3',
        'ti-layout-column2' => 'ti-layout-column2',
        'ti-layout-accordion-separated' => 'ti-layout-accordion-separated',
        'ti-layout-accordion-merged' => 'ti-layout-accordion-merged',
        'ti-layout-accordion-list' => 'ti-layout-accordion-list',
        'ti-ink-pen' => 'ti-ink-pen',
        'ti-info-alt' => 'ti-info-alt',
        'ti-help-alt' => 'ti-help-alt',
        'ti-headphone-alt' => 'ti-headphone-alt',
        'ti-hand-point-up' => 'ti-hand-point-up',
        'ti-hand-point-right' => 'ti-hand-point-right',
        'ti-hand-point-left' => 'ti-hand-point-left',
        'ti-hand-point-down' => 'ti-hand-point-down',
        'ti-gallery' => 'ti-gallery',
        'ti-face-smile' => 'ti-face-smile',
        'ti-face-sad' => 'ti-face-sad',
        'ti-credit-card' => 'ti-credit-card',
        'ti-control-skip-forward' => 'ti-control-skip-forward',
        'ti-control-skip-backward' => 'ti-control-skip-backward',
        'ti-control-record' => 'ti-control-record',
        'ti-control-eject' => 'ti-control-eject',
        'ti-comments-smiley' => 'ti-comments-smiley',
        'ti-brush-alt' => 'ti-brush-alt',
        'ti-youtube' => 'ti-youtube',
        'ti-vimeo' => 'ti-vimeo',
        'ti-twitter' => 'ti-twitter',
        'ti-time' => 'ti-time',
        'ti-tumblr' => 'ti-tumblr',
        'ti-skype' => 'ti-skype',
        'ti-share' => 'ti-share',
        'ti-share-alt' => 'ti-share-alt',
        'ti-rocket' => 'ti-rocket',
        'ti-pinterest' => 'ti-pinterest',
        'ti-new-window' => 'ti-new-window',
        'ti-microsoft' => 'ti-microsoft',
        'ti-list-ol' => 'ti-list-ol',
        'ti-linkedin' => 'ti-linkedin',
        'ti-layout-sidebar-2' => 'ti-layout-sidebar-2',
        'ti-layout-grid4-alt' => 'ti-layout-grid4-alt',
        'ti-layout-grid3-alt' => 'ti-layout-grid3-alt',
        'ti-layout-grid2-alt' => 'ti-layout-grid2-alt',
        'ti-layout-column4-alt' => 'ti-layout-column4-alt',
        'ti-layout-column3-alt' => 'ti-layout-column3-alt',
        'ti-layout-column2-alt' => 'ti-layout-column2-alt',
        'ti-instagram' => 'ti-instagram',
        'ti-google' => 'ti-google',
        'ti-github' => 'ti-github',
        'ti-flickr' => 'ti-flickr',
        'ti-facebook' => 'ti-facebook',
        'ti-dropbox' => 'ti-dropbox',
        'ti-dribbble' => 'ti-dribbble',
        'ti-apple' => 'ti-apple',
        'ti-android' => 'ti-android',
        'ti-save' => 'ti-save',
        'ti-save-alt' => 'ti-save-alt',
        'ti-yahoo' => 'ti-yahoo',
        'ti-wordpress' => 'ti-wordpress',
        'ti-vimeo-alt' => 'ti-vimeo-alt',
        'ti-twitter-alt' => 'ti-twitter-alt',
        'ti-tumblr-alt' => 'ti-tumblr-alt',
        'ti-trello' => 'ti-trello',
        'ti-stack-overflow' => 'ti-stack-overflow',
        'ti-soundcloud' => 'ti-soundcloud',
        'ti-sharethis' => 'ti-sharethis',
        'ti-sharethis-alt' => 'ti-sharethis-alt',
        'ti-reddit' => 'ti-reddit',
        'ti-pinterest-alt' => 'ti-pinterest-alt',
        'ti-microsoft-alt' => 'ti-microsoft-alt',
        'ti-linux' => 'ti-linux',
        'ti-jsfiddle' => 'ti-jsfiddle',
        'ti-joomla' => 'ti-joomla',
        'ti-html5' => 'ti-html5',
        'ti-flickr-alt' => 'ti-flickr-alt',
        'ti-email' => 'ti-email',
        'ti-drupal' => 'ti-drupal',
        'ti-dropbox-alt' => 'ti-dropbox-alt',
        'ti-css3' => 'ti-css3',
        'ti-rss' => 'ti-rss',
        'ti-rss-alt' => 'ti-rss-alt',
    ];
}

function theme_fa_icons() {
    return [
        
        // Font Awesome Social
        'fa fa-facebook',
        'fa fa-facebook-official',
        'fa fa-facebook-square',
        'fa fa-google',
        'fa fa-google-plus',
        'fa fa-google-plus-official',
        'fa fa-google-plus-square',
        'fa fa-instagram',
        'fa fa-linkedin',
        'fa fa-linkedin-square',
        'fa fa-pinterest',
        'fa fa-pinterest-p',
        'fa fa-pinterest-square',
        'fa fa-slack',
        'fa fa-twitter',
        'fa fa-twitter-square',
        'fa fa-youtube',
        'fa fa-youtube-play',
        'fa fa-youtube-square',
        'fa fa-500px',
        'fa fa-address-book',
        'fa fa-address-book-o',
        'fa fa-address-card',
        'fa fa-address-card-o',
        'fa fa-adjust',
        'fa fa-adn',
        'fa fa-align-center',
        'fa fa-align-justify',
        'fa fa-align-left',
        'fa fa-align-right',
        'fa fa-amazon',
        'fa fa-ambulance',
        'fa fa-american-sign-language-interpreting',
        'fa fa-anchor',
        'fa fa-android',
        'fa fa-angellist',
        'fa fa-angle-double-down',
        'fa fa-angle-double-left',
        'fa fa-angle-double-right',
        'fa fa-angle-double-up',
        'fa fa-angle-down',
        'fa fa-angle-left',
        'fa fa-angle-right',
        'fa fa-angle-up',
        'fa fa-apple',
        'fa fa-archive',
        'fa fa-area-chart',
        'fa fa-arrow-circle-down',
        'fa fa-arrow-circle-left',
        'fa fa-arrow-circle-o-down',
        'fa fa-arrow-circle-o-left',
        'fa fa-arrow-circle-o-right',
        'fa fa-arrow-circle-o-up',
        'fa fa-arrow-circle-right',
        'fa fa-arrow-circle-up',
        'fa fa-arrow-down',
        'fa fa-arrow-left',
        'fa fa-arrow-right',
        'fa fa-arrow-up',
        'fa fa-arrows',
        'fa fa-arrows-alt',
        'fa fa-arrows-h',
        'fa fa-arrows-v',
        'fa fa-asl-interpreting',
        'fa fa-assistive-listening-systems',
        'fa fa-asterisk',
        'fa fa-at',
        'fa fa-audio-description',
        'fa fa-automobile',
        'fa fa-backward',
        'fa fa-balance-scale',
        'fa fa-ban',
        'fa fa-bandcamp',
        'fa fa-bank',
        'fa fa-bar-chart',
        'fa fa-bar-chart-o',
        'fa fa-barcode',
        'fa fa-bars',
        'fa fa-bath',
        'fa fa-bathtub',
        'fa fa-battery',
        'fa fa-battery-0',
        'fa fa-battery-1',
        'fa fa-battery-2',
        'fa fa-battery-3',
        'fa fa-battery-4',
        'fa fa-battery-empty',
        'fa fa-battery-full',
        'fa fa-battery-half',
        'fa fa-battery-quarter',
        'fa fa-battery-three-quarters',
        'fa fa-bed',
        'fa fa-beer',
        'fa fa-behance',
        'fa fa-behance-square',
        'fa fa-bell',
        'fa fa-bell-o',
        'fa fa-bell-slash',
        'fa fa-bell-slash-o',
        'fa fa-bicycle',
        'fa fa-binoculars',
        'fa fa-birthday-cake',
        'fa fa-bitbucket',
        'fa fa-bitbucket-square',
        'fa fa-bitcoin',
        'fa fa-black-tie',
        'fa fa-blind',
        'fa fa-bluetooth',
        'fa fa-bluetooth-b',
        'fa fa-bold',
        'fa fa-bolt',
        'fa fa-bomb',
        'fa fa-book',
        'fa fa-bookmark',
        'fa fa-bookmark-o',
        'fa fa-braille',
        'fa fa-briefcase',
        'fa fa-btc',
        'fa fa-bug',
        'fa fa-building',
        'fa fa-building-o',
        'fa fa-bullhorn',
        'fa fa-bullseye',
        'fa fa-bus',
        'fa fa-buysellads',
        'fa fa-cab',
        'fa fa-calculator',
        'fa fa-calendar',
        'fa fa-calendar-check-o',
        'fa fa-calendar-minus-o',
        'fa fa-calendar-o',
        'fa fa-calendar-plus-o',
        'fa fa-calendar-times-o',
        'fa fa-camera',
        'fa fa-camera-retro',
        'fa fa-car',
        'fa fa-caret-down',
        'fa fa-caret-left',
        'fa fa-caret-right',
        'fa fa-caret-square-o-down',
        'fa fa-caret-square-o-left',
        'fa fa-caret-square-o-right',
        'fa fa-caret-square-o-up',
        'fa fa-caret-up',
        'fa fa-cart-arrow-down',
        'fa fa-cart-plus',
        'fa fa-cc',
        'fa fa-cc-amex',
        'fa fa-cc-diners-club',
        'fa fa-cc-discover',
        'fa fa-cc-jcb',
        'fa fa-cc-mastercard',
        'fa fa-cc-paypal',
        'fa fa-cc-stripe',
        'fa fa-cc-visa',
        'fa fa-certificate',
        'fa fa-chain',
        'fa fa-chain-broken',
        'fa fa-check',
        'fa fa-check-circle',
        'fa fa-check-circle-o',
        'fa fa-check-square',
        'fa fa-check-square-o',
        'fa fa-chevron-circle-down',
        'fa fa-chevron-circle-left',
        'fa fa-chevron-circle-right',
        'fa fa-chevron-circle-up',
        'fa fa-chevron-down',
        'fa fa-chevron-left',
        'fa fa-chevron-right',
        'fa fa-chevron-up',
        'fa fa-child',
        'fa fa-chrome',
        'fa fa-circle',
        'fa fa-circle-o',
        'fa fa-circle-o-notch',
        'fa fa-circle-thin',
        'fa fa-clipboard',
        'fa fa-clock-o',
        'fa fa-clone',
        'fa fa-close',
        'fa fa-cloud',
        'fa fa-cloud-download',
        'fa fa-cloud-upload',
        'fa fa-cny',
        'fa fa-code',
        'fa fa-code-fork',
        'fa fa-codepen',
        'fa fa-codiepie',
        'fa fa-coffee',
        'fa fa-cog',
        'fa fa-cogs',
        'fa fa-columns',
        'fa fa-comment',
        'fa fa-comment-o',
        'fa fa-commenting',
        'fa fa-commenting-o',
        'fa fa-comments',
        'fa fa-comments-o',
        'fa fa-compass',
        'fa fa-compress',
        'fa fa-connectdevelop',
        'fa fa-contao',
        'fa fa-copy',
        'fa fa-copyright',
        'fa fa-creative-commons',
        'fa fa-credit-card',
        'fa fa-credit-card-alt',
        'fa fa-crop',
        'fa fa-crosshairs',
        'fa fa-css3',
        'fa fa-cube',
        'fa fa-cubes',
        'fa fa-cut',
        'fa fa-cutlery',
        'fa fa-dashboard',
        'fa fa-dashcube',
        'fa fa-database',
        'fa fa-deaf',
        'fa fa-deafness',
        'fa fa-dedent',
        'fa fa-delicious',
        'fa fa-desktop',
        'fa fa-deviantart',
        'fa fa-diamond',
        'fa fa-digg',
        'fa fa-dollar',
        'fa fa-dot-circle-o',
        'fa fa-download',
        'fa fa-dribbble',
        'fa fa-drivers-license',
        'fa fa-drivers-license-o',
        'fa fa-dropbox',
        'fa fa-drupal',
        'fa fa-edge',
        'fa fa-edit',
        'fa fa-eercast',
        'fa fa-eject',
        'fa fa-ellipsis-h',
        'fa fa-ellipsis-v',
        'fa fa-empire',
        'fa fa-envelope',
        'fa fa-envelope-o',
        'fa fa-envelope-open',
        'fa fa-envelope-open-o',
        'fa fa-envelope-square',
        'fa fa-envira',
        'fa fa-eraser',
        'fa fa-etsy',
        'fa fa-eur',
        'fa fa-euro',
        'fa fa-exchange',
        'fa fa-exclamation',
        'fa fa-exclamation-circle',
        'fa fa-exclamation-triangle',
        'fa fa-expand',
        'fa fa-expeditedssl',
        'fa fa-external-link',
        'fa fa-external-link-square',
        'fa fa-eye',
        'fa fa-eye-slash',
        'fa fa-eyedropper',
        'fa fa-fa',
        'fa fa-facebook',
        'fa fa-facebook-f',
        'fa fa-facebook-official',
        'fa fa-facebook-square',
        'fa fa-fast-backward',
        'fa fa-fast-forward',
        'fa fa-fax',
        'fa fa-feed',
        'fa fa-female',
        'fa fa-fighter-jet',
        'fa fa-file',
        'fa fa-file-archive-o',
        'fa fa-file-audio-o',
        'fa fa-file-code-o',
        'fa fa-file-excel-o',
        'fa fa-file-image-o',
        'fa fa-file-movie-o',
        'fa fa-file-o',
        'fa fa-file-pdf-o',
        'fa fa-file-photo-o',
        'fa fa-file-picture-o',
        'fa fa-file-powerpoint-o',
        'fa fa-file-sound-o',
        'fa fa-file-text',
        'fa fa-file-text-o',
        'fa fa-file-video-o',
        'fa fa-file-word-o',
        'fa fa-file-zip-o',
        'fa fa-files-o',
        'fa fa-film',
        'fa fa-filter',
        'fa fa-fire',
        'fa fa-fire-extinguisher',
        'fa fa-firefox',
        'fa fa-first-order',
        'fa fa-flag',
        'fa fa-flag-checkered',
        'fa fa-flag-o',
        'fa fa-flash',
        'fa fa-flask',
        'fa fa-flickr',
        'fa fa-floppy-o',
        'fa fa-folder',
        'fa fa-folder-o',
        'fa fa-folder-open',
        'fa fa-folder-open-o',
        'fa fa-font',
        'fa fa-font-awesome',
        'fa fa-fonticons',
        'fa fa-fort-awesome',
        'fa fa-forumbee',
        'fa fa-forward',
        'fa fa-foursquare',
        'fa fa-free-code-camp',
        'fa fa-frown-o',
        'fa fa-futbol-o',
        'fa fa-gamepad',
        'fa fa-gavel',
        'fa fa-gbp',
        'fa fa-ge',
        'fa fa-gear',
        'fa fa-gears',
        'fa fa-genderless',
        'fa fa-get-pocket',
        'fa fa-gg',
        'fa fa-gg-circle',
        'fa fa-gift',
        'fa fa-git',
        'fa fa-git-square',
        'fa fa-github',
        'fa fa-github-alt',
        'fa fa-github-square',
        'fa fa-gitlab',
        'fa fa-gittip',
        'fa fa-glass',
        'fa fa-glide',
        'fa fa-glide-g',
        'fa fa-globe',
        'fa fa-google',
        'fa fa-google-plus',
        'fa fa-google-plus-circle',
        'fa fa-google-plus-official',
        'fa fa-google-plus-square',
        'fa fa-google-wallet',
        'fa fa-graduation-cap',
        'fa fa-gratipay',
        'fa fa-grav',
        'fa fa-group',
        'fa fa-h-square',
        'fa fa-hacker-news',
        'fa fa-hand-grab-o',
        'fa fa-hand-lizard-o',
        'fa fa-hand-o-down',
        'fa fa-hand-o-left',
        'fa fa-hand-o-right',
        'fa fa-hand-o-up',
        'fa fa-hand-paper-o',
        'fa fa-hand-peace-o',
        'fa fa-hand-pointer-o',
        'fa fa-hand-rock-o',
        'fa fa-hand-scissors-o',
        'fa fa-hand-spock-o',
        'fa fa-hand-stop-o',
        'fa fa-handshake-o',
        'fa fa-hard-of-hearing',
        'fa fa-hashtag',
        'fa fa-hdd-o',
        'fa fa-header',
        'fa fa-headphones',
        'fa fa-heart',
        'fa fa-heart-o',
        'fa fa-heartbeat',
        'fa fa-history',
        'fa fa-home',
        'fa fa-hospital-o',
        'fa fa-hotel',
        'fa fa-hourglass',
        'fa fa-hourglass-1',
        'fa fa-hourglass-2',
        'fa fa-hourglass-3',
        'fa fa-hourglass-end',
        'fa fa-hourglass-half',
        'fa fa-hourglass-o',
        'fa fa-hourglass-start',
        'fa fa-houzz',
        'fa fa-html5',
        'fa fa-i-cursor',
        'fa fa-id-badge',
        'fa fa-id-card',
        'fa fa-id-card-o',
        'fa fa-ils',
        'fa fa-image',
        'fa fa-imdb',
        'fa fa-inbox',
        'fa fa-indent',
        'fa fa-industry',
        'fa fa-info',
        'fa fa-info-circle',
        'fa fa-inr',
        'fa fa-instagram',
        'fa fa-institution',
        'fa fa-internet-explorer',
        'fa fa-intersex',
        'fa fa-ioxhost',
        'fa fa-italic',
        'fa fa-joomla',
        'fa fa-jpy',
        'fa fa-jsfiddle',
        'fa fa-key',
        'fa fa-keyboard-o',
        'fa fa-krw',
        'fa fa-language',
        'fa fa-laptop',
        'fa fa-lastfm',
        'fa fa-lastfm-square',
        'fa fa-leaf',
        'fa fa-leanpub',
        'fa fa-legal',
        'fa fa-lemon-o',
        'fa fa-level-down',
        'fa fa-level-up',
        'fa fa-life-bouy',
        'fa fa-life-buoy',
        'fa fa-life-ring',
        'fa fa-life-saver',
        'fa fa-lightbulb-o',
        'fa fa-line-chart',
        'fa fa-link',
        'fa fa-linkedin',
        'fa fa-linkedin-square',
        'fa fa-linode',
        'fa fa-linux',
        'fa fa-list',
        'fa fa-list-alt',
        'fa fa-list-ol',
        'fa fa-list-ul',
        'fa fa-location-arrow',
        'fa fa-lock',
        'fa fa-long-arrow-down',
        'fa fa-long-arrow-left',
        'fa fa-long-arrow-right',
        'fa fa-long-arrow-up',
        'fa fa-low-vision',
        'fa fa-magic',
        'fa fa-magnet',
        'fa fa-mail-forward',
        'fa fa-mail-reply',
        'fa fa-mail-reply-all',
        'fa fa-male',
        'fa fa-map',
        'fa fa-map-marker',
        'fa fa-map-o',
        'fa fa-map-pin',
        'fa fa-map-signs',
        'fa fa-mars',
        'fa fa-mars-double',
        'fa fa-mars-stroke',
        'fa fa-mars-stroke-h',
        'fa fa-mars-stroke-v',
        'fa fa-maxcdn',
        'fa fa-meanpath',
        'fa fa-medium',
        'fa fa-medkit',
        'fa fa-meetup',
        'fa fa-meh-o',
        'fa fa-mercury',
        'fa fa-microchip',
        'fa fa-microphone',
        'fa fa-microphone-slash',
        'fa fa-minus',
        'fa fa-minus-circle',
        'fa fa-minus-square',
        'fa fa-minus-square-o',
        'fa fa-mixcloud',
        'fa fa-mobile',
        'fa fa-mobile-phone',
        'fa fa-modx',
        'fa fa-money',
        'fa fa-moon-o',
        'fa fa-mortar-board',
        'fa fa-motorcycle',
        'fa fa-mouse-pointer',
        'fa fa-music',
        'fa fa-navicon',
        'fa fa-neuter',
        'fa fa-newspaper-o',
        'fa fa-object-group',
        'fa fa-object-ungroup',
        'fa fa-odnoklassniki',
        'fa fa-odnoklassniki-square',
        'fa fa-opencart',
        'fa fa-openid',
        'fa fa-opera',
        'fa fa-optin-monster',
        'fa fa-outdent',
        'fa fa-pagelines',
        'fa fa-paint-brush',
        'fa fa-paper-plane',
        'fa fa-paper-plane-o',
        'fa fa-paperclip',
        'fa fa-paragraph',
        'fa fa-paste',
        'fa fa-pause',
        'fa fa-pause-circle',
        'fa fa-pause-circle-o',
        'fa fa-paw',
        'fa fa-paypal',
        'fa fa-pencil',
        'fa fa-pencil-square',
        'fa fa-pencil-square-o',
        'fa fa-percent',
        'fa fa-phone',
        'fa fa-phone-square',
        'fa fa-photo',
        'fa fa-picture-o',
        'fa fa-pie-chart',
        'fa fa-pied-piper',
        'fa fa-pied-piper-alt',
        'fa fa-pied-piper-pp',
        'fa fa-pinterest',
        'fa fa-pinterest-p',
        'fa fa-pinterest-square',
        'fa fa-plane',
        'fa fa-play',
        'fa fa-play-circle',
        'fa fa-play-circle-o',
        'fa fa-plug',
        'fa fa-plus',
        'fa fa-plus-circle',
        'fa fa-plus-square',
        'fa fa-plus-square-o',
        'fa fa-podcast',
        'fa fa-power-off',
        'fa fa-print',
        'fa fa-product-hunt',
        'fa fa-pull-left',
        'fa fa-pull-right',
        'fa fa-puzzle-piece',
        'fa fa-qq',
        'fa fa-qrcode',
        'fa fa-question',
        'fa fa-question-circle',
        'fa fa-question-circle-o',
        'fa fa-quora',
        'fa fa-quote-left',
        'fa fa-quote-right',
        'fa fa-ra',
        'fa fa-random',
        'fa fa-ravelry',
        'fa fa-rebel',
        'fa fa-recycle',
        'fa fa-reddit',
        'fa fa-reddit-alien',
        'fa fa-reddit-square',
        'fa fa-refresh',
        'fa fa-registered',
        'fa fa-remove',
        'fa fa-renren',
        'fa fa-reorder',
        'fa fa-repeat',
        'fa fa-reply',
        'fa fa-reply-all',
        'fa fa-resistance',
        'fa fa-retweet',
        'fa fa-rmb',
        'fa fa-road',
        'fa fa-rocket',
        'fa fa-rotate-left',
        'fa fa-rotate-right',
        'fa fa-rouble',
        'fa fa-rss',
        'fa fa-rss-square',
        'fa fa-rub',
        'fa fa-ruble',
        'fa fa-rupee',
        'fa fa-s15',
        'fa fa-safari',
        'fa fa-save',
        'fa fa-scissors',
        'fa fa-scribd',
        'fa fa-search',
        'fa fa-search-minus',
        'fa fa-search-plus',
        'fa fa-sellsy',
        'fa fa-send',
        'fa fa-send-o',
        'fa fa-server',
        'fa fa-share',
        'fa fa-share-alt',
        'fa fa-share-alt-square',
        'fa fa-share-square',
        'fa fa-share-square-o',
        'fa fa-shekel',
        'fa fa-sheqel',
        'fa fa-shield',
        'fa fa-ship',
        'fa fa-shirtsinbulk',
        'fa fa-shopping-bag',
        'fa fa-shopping-basket',
        'fa fa-shopping-cart',
        'fa fa-shower',
        'fa fa-sign-in',
        'fa fa-sign-language',
        'fa fa-sign-out',
        'fa fa-signal',
        'fa fa-signing',
        'fa fa-simplybuilt',
        'fa fa-sitemap',
        'fa fa-skyatlas',
        'fa fa-skype',
        'fa fa-slack',
        'fa fa-sliders',
        'fa fa-slideshare',
        'fa fa-smile-o',
        'fa fa-snapchat',
        'fa fa-snapchat-ghost',
        'fa fa-snapchat-square',
        'fa fa-snowflake-o',
        'fa fa-soccer-ball-o',
        'fa fa-sort',
        'fa fa-sort-alpha-asc',
        'fa fa-sort-alpha-desc',
        'fa fa-sort-amount-asc',
        'fa fa-sort-amount-desc',
        'fa fa-sort-asc',
        'fa fa-sort-desc',
        'fa fa-sort-down',
        'fa fa-sort-numeric-asc',
        'fa fa-sort-numeric-desc',
        'fa fa-sort-up',
        'fa fa-soundcloud',
        'fa fa-space-shuttle',
        'fa fa-spinner',
        'fa fa-spoon',
        'fa fa-spotify',
        'fa fa-square',
        'fa fa-square-o',
        'fa fa-stack-exchange',
        'fa fa-stack-overflow',
        'fa fa-star',
        'fa fa-star-half',
        'fa fa-star-half-empty',
        'fa fa-star-half-full',
        'fa fa-star-half-o',
        'fa fa-star-o',
        'fa fa-steam',
        'fa fa-steam-square',
        'fa fa-step-backward',
        'fa fa-step-forward',
        'fa fa-stethoscope',
        'fa fa-sticky-note',
        'fa fa-sticky-note-o',
        'fa fa-stop',
        'fa fa-stop-circle',
        'fa fa-stop-circle-o',
        'fa fa-street-view',
        'fa fa-strikethrough',
        'fa fa-stumbleupon',
        'fa fa-stumbleupon-circle',
        'fa fa-subscript',
        'fa fa-subway',
        'fa fa-suitcase',
        'fa fa-sun-o',
        'fa fa-superpowers',
        'fa fa-superscript',
        'fa fa-support',
        'fa fa-table',
        'fa fa-tablet',
        'fa fa-tachometer',
        'fa fa-tag',
        'fa fa-tags',
        'fa fa-tasks',
        'fa fa-taxi',
        'fa fa-telegram',
        'fa fa-television',
        'fa fa-tencent-weibo',
        'fa fa-terminal',
        'fa fa-text-height',
        'fa fa-text-width',
        'fa fa-th',
        'fa fa-th-large',
        'fa fa-th-list',
        'fa fa-themeisle',
        'fa fa-thermometer',
        'fa fa-thermometer-0',
        'fa fa-thermometer-1',
        'fa fa-thermometer-2',
        'fa fa-thermometer-3',
        'fa fa-thermometer-4',
        'fa fa-thermometer-empty',
        'fa fa-thermometer-full',
        'fa fa-thermometer-half',
        'fa fa-thermometer-quarter',
        'fa fa-thermometer-three-quarters',
        'fa fa-thumb-tack',
        'fa fa-thumbs-down',
        'fa fa-thumbs-o-down',
        'fa fa-thumbs-o-up',
        'fa fa-thumbs-up',
        'fa fa-ticket',
        'fa fa-times',
        'fa fa-times-circle',
        'fa fa-times-circle-o',
        'fa fa-times-rectangle',
        'fa fa-times-rectangle-o',
        'fa fa-tint',
        'fa fa-toggle-down',
        'fa fa-toggle-left',
        'fa fa-toggle-off',
        'fa fa-toggle-on',
        'fa fa-toggle-right',
        'fa fa-toggle-up',
        'fa fa-trademark',
        'fa fa-train',
        'fa fa-transgender',
        'fa fa-transgender-alt',
        'fa fa-trash',
        'fa fa-trash-o',
        'fa fa-tree',
        'fa fa-trello',
        'fa fa-tripadvisor',
        'fa fa-trophy',
        'fa fa-truck',
        'fa fa-try',
        'fa fa-tty',
        'fa fa-tumblr',
        'fa fa-tumblr-square',
        'fa fa-turkish-lira',
        'fa fa-tv',
        'fa fa-twitch',
        'fa fa-twitter',
        'fa fa-twitter-square',
        'fa fa-umbrella',
        'fa fa-underline',
        'fa fa-undo',
        'fa fa-universal-access',
        'fa fa-university',
        'fa fa-unlink',
        'fa fa-unlock',
        'fa fa-unlock-alt',
        'fa fa-unsorted',
        'fa fa-upload',
        'fa fa-usb',
        'fa fa-usd',
        'fa fa-user',
        'fa fa-user-circle',
        'fa fa-user-circle-o',
        'fa fa-user-md',
        'fa fa-user-o',
        'fa fa-user-plus',
        'fa fa-user-secret',
        'fa fa-user-times',
        'fa fa-users',
        'fa fa-vcard',
        'fa fa-vcard-o',
        'fa fa-venus',
        'fa fa-venus-double',
        'fa fa-venus-mars',
        'fa fa-viacoin',
        'fa fa-viadeo',
        'fa fa-viadeo-square',
        'fa fa-video-camera',
        'fa fa-vimeo',
        'fa fa-vimeo-square',
        'fa fa-vine',
        'fa fa-vk',
        'fa fa-volume-control-phone',
        'fa fa-volume-down',
        'fa fa-volume-off',
        'fa fa-volume-up',
        'fa fa-warning',
        'fa fa-wechat',
        'fa fa-weibo',
        'fa fa-weixin',
        'fa fa-whatsapp',
        'fa fa-wheelchair',
        'fa fa-wheelchair-alt',
        'fa fa-wifi',
        'fa fa-wikipedia-w',
        'fa fa-window-close',
        'fa fa-window-close-o',
        'fa fa-window-maximize',
        'fa fa-window-minimize',
        'fa fa-window-restore',
        'fa fa-windows',
        'fa fa-won',
        'fa fa-wordpress',
        'fa fa-wpbeginner',
        'fa fa-wpexplorer',
        'fa fa-wpforms',
        'fa fa-wrench',
        'fa fa-xing',
        'fa fa-xing-square',
        'fa fa-y-combinator',
        'fa fa-y-combinator-square',
        'fa fa-yahoo',
        'fa fa-yc',
        'fa fa-yc-square',
        'fa fa-yelp',
        'fa fa-yen',
        'fa fa-yoast',
        'fa fa-youtube',
        'fa fa-youtube-play',
        'fa fa-youtube-square',
    ];
}

